version: "3.8"

services:
  laravel_franken:
    image: heshcp78/laravel-franken:266752f6a1b79d334aea2ca86dea5738e65dc226
    ports:
      - "8002:8002"
    env_file:
      - ./backend/.env
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    depends_on:
      - mysql
      - faceapi

  faceapi:
    image: heshcp78/faceapi:266752f6a1b79d334aea2ca86dea5738e65dc226
    ports:
      - "5000:5000"
    volumes:
      - face_known_faces:/app/known_faces
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  mysql:
    image: mysql:8.4.4
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: web_presensi_facerecognation
      MYSQL_ROOT_HOST: '%'
    volumes:
      - mysql_data:/var/lib/mysql
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - prometheus_data:/prometheus
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

volumes:
  mysql_data:
  face_known_faces:
  prometheus_data:
  grafana_data: