services:
  laravel_franken:
    build: ./backend
    ports:
      - "8002:8002"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    depends_on:
      - mysql
      - faceapi

  # MySQL database
  mysql:
    image: mysql:8.4.4
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: web_presensi_facerecognation
    volumes:
      - mysql_data:/var/lib/mysql

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - mysql

  faceapi:
    build:
      context: ./face_detection
    ports:
      - "5000:5000"
    volumes:
      - ./face_detection/known_faces:/app/known_faces
    restart: always

volumes:
  mysql_data:
