global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'laravel'
    static_configs:
      - targets: ['laravel_franken:8002'] # ganti sesuai endpoint metrics jika ada

  - job_name: 'faceapi'
    static_configs:
      - targets: ['faceapi:5000'] # hanya jika faceapi punya endpoint metrics

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']